config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.capturaweb.urls")),
]

core/capturaweb/urls.py
from django.urls import path

from core.capturaweb.tiempo import get_tiempo
from .views import CapturaView, ProgramarGrabacion, BorrarGrabacionView, UpdateGrabacionView, stream_view, \
    GrabacionesProgramadasListView, GrabacionesProgramadasSchedulerListView

urlpatterns = [
    path("", CapturaView.as_view(), name="capturaweb"),
    path("programar/", ProgramarGrabacion.as_view(), name="programar"),
    path("grabaciones_programadas/", GrabacionesProgramadasListView.as_view(), name="grabaciones_programadas"),
    path("scheduler/", GrabacionesProgramadasSchedulerListView.as_view(), name="scheduler"),
    path("borrar/<pk>/", BorrarGrabacionView.as_view(), name="borrar"),
    path("editar/<pk>/", UpdateGrabacionView.as_view(), name="editar"),
    path("get_tiempo", get_tiempo, name="get_tiempo"),
    path('stream/', stream_view, name='stream_url'),
]
# if settings.DEBUG:
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/capturaweb/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Q


class Grabacion(models.Model):
    titulo = models.CharField(max_length=100)
    duracion = models.DurationField(default=0)
    convertida = models.BooleanField(verbose_name="Convertir", default=False)
    tipo_grabacion = models.IntegerField(verbose_name="Tipo", default=1)

    def __str__(self):
        return self.titulo


class DatosGrabadora(models.Model):
    nombre = models.CharField(verbose_name="Nombre de la capturadora", max_length=100)
    placa = models.CharField(verbose_name="Modelo de la placa", max_length=100)
    formato = models.CharField(verbose_name="Formato de grabacion", max_length=2)
    directorio_de_grabacion = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre


class GrabacionProgramada(models.Model):
    titulo = models.CharField(max_length=100)
    convertida = models.BooleanField(verbose_name="Convertir", default=False)
    tipo_grabacion = models.IntegerField(verbose_name="Tipo", default=1)
    segmento = models.IntegerField(verbose_name="Segmento", default=60)
    lunes = models.BooleanField("Lunes", default=None)
    martes = models.BooleanField("Martes", default=None)
    miercoles = models.BooleanField("Miercoles", default=None)
    jueves = models.BooleanField("Jueves", default=None)
    viernes = models.BooleanField("Viernes", default=None)
    sabado = models.BooleanField("Sabado", default=None)
    domingo = models.BooleanField("Domingo", default=None)
    hora_inicio = models.TimeField()
    hora_fin = models.TimeField()
    activa = models.BooleanField("Activa", default=True)

    def __str__(self):
        return f"{self.titulo} - {self.hora_inicio} a {self.hora_fin}"

    def clean(self):
        super(GrabacionProgramada, self).clean()

        # Construir la consulta para verificar superposiciones
        consulta_superposiciones = Q()
        dias_semana = ['lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado', 'domingo']

        for dia in dias_semana:
            if getattr(self, dia):
                consulta_superposiciones |= Q(
                    **{dia: True, 'hora_inicio__lt': self.hora_fin, 'hora_fin__gt': self.hora_inicio})

        superposiciones = GrabacionProgramada.objects.filter(consulta_superposiciones).exclude(id=self.id)

        if superposiciones.exists():
            grabaciones_superpuestas = list(superposiciones)
            mensaje = 'La grabación se superpone con las siguientes grabaciones programadas:\n'
            for grabacion in grabaciones_superpuestas:
                mensaje += f'- {grabacion.titulo} ({grabacion.hora_inicio}-{grabacion.hora_fin})\n'
            raise ValidationError(mensaje)

    def get_dias_semana(self):
        dias = []
        if self.lunes:
            dias.append('mon')
        if self.martes:
            dias.append('tue')
        if self.miercoles:
            dias.append('wed')
        if self.jueves:
            dias.append('thu')
        if self.viernes:
            dias.append('fri')
        if self.sabado:
            dias.append('sat')
        if self.domingo:
            dias.append('sun')
        return ",".join(dias)

core/capturaweb/forms.py
from django import forms

from core.capturaweb.models import Grabacion, GrabacionProgramada

FORMATO = ((1, "AUDIO-VIDEO"), (2, "AUDIO"))


class DatosGrabacionForm(forms.ModelForm):
    TIPO = ((1, "CONTINUA"), (2, "SEGMENTADA"))
    CONVERTIR = ((True, "SI"), (False, "NO"))

    tipo_grabacion = forms.ChoiceField(choices=TIPO, initial='1',
                                       widget=forms.RadioSelect(attrs={'class': 'btn-check'}))
    convertida = forms.ChoiceField(choices=CONVERTIR, initial=False,
                                   widget=forms.RadioSelect(attrs={'class': 'btn-check'}))
    segmento = forms.CharField(max_length=4, initial=10, required=False,
                               widget=forms.TextInput(attrs={'style': 'visibility: hidden;'}))

    class Meta:
        model = Grabacion
        fields = ['titulo', 'convertida', 'tipo_grabacion']
        widgets = {
            'titulo': forms.TextInput(attrs={'class': 'form-control'}),
        }


class ProgramarGrabacionForm(forms.ModelForm):
    TIPO = ((1, "CONTINUA"), (2, "SEGMENTADA"))
    CONVERTIR = ((True, "SI"), (False, "NO"))

    tipo_grabacion = forms.ChoiceField(choices=TIPO, initial='1',
                                       widget=forms.RadioSelect(attrs={'class': 'btn-check'}))
    convertida = forms.ChoiceField(choices=CONVERTIR, initial=False,
                                   widget=forms.RadioSelect(attrs={'class': 'btn-check'}))
    segmento = forms.CharField(max_length=4, initial=60, required=False,
                               widget=forms.TextInput(attrs={'class': 'form-control', 'style': 'visibility: hidden;'}))

    class Meta:
        model = GrabacionProgramada
        fields = ['titulo', 'hora_inicio', 'hora_fin', 'lunes', 'martes', 'miercoles', 'jueves', 'viernes',
                  'sabado', 'domingo', 'convertida', 'tipo_grabacion', 'activa']
        widgets = {
            'titulo': forms.TextInput(attrs={'class': 'form-control'}),
            'hora_inicio': forms.TimeInput(
                attrs={'class': 'form-control',
                       'placeholder': 'Select a date',
                       'type': 'time'
                       }),
            'hora_fin': forms.TimeInput(
                attrs={'class': 'form-control',
                       'placeholder': 'Select a date',
                       'type': 'time'
                       }),
            'lunes': forms.CheckboxInput(
                attrs={'class': 'btn-check',
                       'type': 'checkbox'
                       }),
            'martes': forms.CheckboxInput(
                attrs={'class': 'btn-check',
                       'type': 'checkbox'
                       }),
            'miercoles': forms.CheckboxInput(
                attrs={'class': 'btn-check',
                       'type': 'checkbox'
                       }),
            'jueves': forms.CheckboxInput(
                attrs={'class': 'btn-check',
                       'type': 'checkbox'
                       }),
            'viernes': forms.CheckboxInput(
                attrs={'class': 'btn-check',
                       'type': 'checkbox'
                       }),
            'sabado': forms.CheckboxInput(
                attrs={'class': 'btn-check',
                       'type': 'checkbox'
                       }),
            'domingo': forms.CheckboxInput(
                attrs={'class': 'btn-check',
                       'type': 'checkbox'
                       }),
            'activa': forms.CheckboxInput(
                attrs={'class': 'btn-check',
                       'type': 'checkbox'
                       }),
        }


class DescargaForm(forms.Form):
    url = forms.CharField(label="URL", max_length=200, required=True)
    formato = forms.ChoiceField(widget=forms.RadioSelect, choices=FORMATO, required=True)

core/capturaweb/views.py
import datetime
import re
import time
import logging

from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.decorators.http import require_http_methods
from django.views.generic import FormView, CreateView, UpdateView, DeleteView
from django.views.generic import ListView

from .conversor import Convertir
from .datos_temp import guardar_datos, obtener_dato, eliminar_datos
from .forms import DatosGrabacionForm, ProgramarGrabacionForm
from .grabacion import Captura
from .models import DatosGrabadora, Grabacion, GrabacionProgramada

logger = logging.getLogger('capturadora')


class CapturaView(FormView):
    template_name = 'capturaweb/grabadora.html'
    form_class = DatosGrabacionForm
    success_url = reverse_lazy('capturaweb')
    grabacion = Captura()
    convertir = Convertir()
    path_temp = '/tmp/grabacion_actual'

    def get_datos_capturadora(self):
        try:
            return DatosGrabadora.objects.all()[0]
        except IndexError:
            return False

    def form_valid(self, form):
        global context
        data = form.cleaned_data
        #zona_hora = datetime.timezone(datetime.timedelta(hours=-3))
        hora_arg = datetime.datetime.now()
        ocupada = self.grabacion.pid_proceso()
        hora = str(hora_arg.hour) + "h" + str(hora_arg.minute) + "m"
        titulo_pos = f'{data.get("titulo").upper()}'
        titulo = re.sub(r'[/. ,]', '_', titulo_pos)

        if 'rec' in self.request.POST:
            if ocupada:
                titulo = obtener_dato(self.path_temp, "titulo")
                messages.error(self.request,
                               f'La grabacion {titulo} está en curso.\n Deténgala antes de comenzar una nueva grabación')
            else:
                guardar_datos(titulo, data.get("tipo_grabacion"), data.get("segmento"), False,
                              data.get("convertida"), "00:00:00")
                nueva_grabacion = Grabacion(titulo=titulo, duracion=datetime.timedelta(hours=0, minutes=0, seconds=0))
                nueva_grabacion.save()
                logger.debug(f"INICIO DE CAPTURA CONTINUA MANUAL - {titulo}")
            time.sleep(2)
            ocupada = self.grabacion.pid_proceso()
            context = self.get_context_data(form=form, ocupada=ocupada, titulo=titulo)
        elif 'stop' in self.request.POST:
            convertir = data.get("convertida")
            if ocupada:
                self.grabacion.stop()
                if convertir == "True":
                    titulo = obtener_dato(self.path_temp, "titulo")
                    self.convertir.para_convertir(titulo)
                eliminar_datos(self.path_temp)
            time.sleep(2)
            context = self.get_context_data(form=form)

        return render(self.request, self.template_name, context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        ocupada = self.grabacion.pid_proceso()
        if ocupada:
            context['ocupada'] = True
            obtener_dato(self.path_temp, 'titulo')
            initial_data = {
                'titulo': obtener_dato(self.path_temp, 'titulo'),
                'tipo_grabacion': obtener_dato(self.path_temp, 'tipo'),
                'segmento': obtener_dato(self.path_temp, 'segmento'),
                'convertida': obtener_dato(self.path_temp, 'convertir'),
            }
            form = DatosGrabacionForm(initial=initial_data)
            context['titulo'] = obtener_dato(self.path_temp, 'titulo'),
            context['form'] = form
        context['grabadora'] = self.get_datos_capturadora().nombre
        context['grabaciones_programadas'] = GrabacionProgramada.objects.all()
        return context


class GrabacionesProgramadasListView(ListView):
    template_name = 'capturaweb/grabaciones_programadas.html'
    model = GrabacionProgramada
    success_url = reverse_lazy('capturaweb')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['anterior'] = 'Inicio'
        context['url_general'] = reverse_lazy('capturaweb')
        context['comentario'] = 'Programe una grabacion automatica'
        context['title_table'] = 'Grabaciones Programadas'
        context['segment'] = 'alumnos'
        context['btn_accion'] = 'Guardar'
        context['title'] = 'Programar'
        return context


@require_http_methods(["GET"])
def stream_view(request):
    stream_url = "rtmp://192.168.2.62:1935/live"
    return HttpResponse(stream_url, content_type="video/mp4")


class ProgramarGrabacion(CreateView):
    model = GrabacionProgramada
    form_class = ProgramarGrabacionForm
    template_name = 'capturaweb/agregar_grabacion.html'
    success_url = reverse_lazy('grabaciones_programadas')

    def form_invalid(self, form):
        response = super().form_invalid(form)
        errors = form.errors['__all__'] if '__all__' in form.errors else None
        return self.render_to_response(self.get_context_data(errors=errors))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['anterior'] = 'Grabaciones Programadas'
        context['url_general'] = reverse_lazy('grabaciones_programadas')
        context['comentario'] = 'Programe una grabacion automatica'
        context['title_table'] = 'Programadas'
        context['segment'] = 'alumnos'
        context['btn_accion'] = 'Guardar'
        context['title'] = 'Programar'
        return context


class UpdateGrabacionView(UpdateView):
    model = GrabacionProgramada
    form_class = ProgramarGrabacionForm
    template_name = 'capturaweb/update_grabacion.html'
    success_url = reverse_lazy('grabaciones_programadas')

    def form_invalid(self, form):
        response = super().form_invalid(form)
        errors = form.errors['__all__'] if '__all__' in form.errors else None
        return self.render_to_response(self.get_context_data(errors=errors))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['anterior'] = 'Inicio'
        context['url_general'] = reverse_lazy('grabaciones_programadas')
        context['comentario'] = 'Programe una grabacion automatica'
        context['title_table'] = 'Programadas'
        context['segment'] = 'alumnos'
        context['btn_accion'] = 'Guardar'
        return context


class BorrarGrabacionView(DeleteView):
    model = GrabacionProgramada
    template_name = 'capturaweb/borrar_grabacion.html'
    success_url = reverse_lazy('grabaciones_programadas')

    def get_grabacion(self):
        return GrabacionProgramada.objects.get(id=self.object.id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comentario'] = f'Se eliminara la grabacion!'
        context['mensaje'] = f'Decea borrar la grabacion {self.get_grabacion()}'
        context['anterior'] = 'Inicio'
        context['url_general'] = reverse_lazy('capturaweb')
        context['btn_accion'] = 'Guardar'
        return context


class GrabacionesProgramadasSchedulerListView(ListView):
    model = GrabacionProgramada
    template_name = 'capturaweb/scheduler.html'
    context_object_name = 'grabaciones'

    def get_queryset(self):
        from .signals import scheduler
        jobs = scheduler.get_jobs()
        grabaciones_programadas = []
        for job in jobs:
            if job.id.startswith('iniciar_grabacion_') or job.id.startswith('parar_grabacion_'):
                grabaciones_programadas.append(job)
        return grabaciones_programadas

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

templates/capturaweb/layouts/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    {% load static %}
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Fonts -->

    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <!--    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>-->


    <!-- Styles -->
    <link href="{% static 'capturadora/vendor/bootstrap/css/bootstrap.css' %}" rel="stylesheet">

    <link href="{% static 'capturadora/css/gestion.css' %}" rel="stylesheet">

    <!-- Fontawesome -->
    <link type="text/css" href="{% static 'capturadora/vendor/@fortawesome/fontawesome-free/css/all.min.css' %}"
          rel="stylesheet">

    <!-- Celular -->
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0"/>

    <script src="{% static 'capturadora/js/jquery-3.6.0.min.js' %}"></script>

    <title>{% block title %}{% endblock %}</title>
    <meta name="description" content="{% block description %}{% endblock %}"/>
 <!-- Incluye la biblioteca de Video.js -->
    <link href="https://vjs.zencdn.net/7.11.4/video-js.css" rel="stylesheet">
    <script src="https://vjs.zencdn.net/7.11.4/video.js"></script>
    {% block head %} {% endblock %}
    <script>
        $(document).ready(function() {
            $("#id_tipo_grabacion_1").click(function() {
                $("#id_segmento").css("visibility", "visible");
            });
            $("#id_tipo_grabacion_0").click(function() {
                $("#id_segmento").css("visibility", "hidden");

            });
        });
    </script>

    <script>
        document.addEventListener("DOMContentLoaded", function() {
            var processStartedListener = function() {
                location.reload();
            };

            var processFinishedListener = function() {
                location.reload();
            };

            jQuery('#some-element').on('process_started', processStartedListener);
            jQuery('#some-element').on('process_finished', processFinishedListener);
        });
    </script>

    {% block extra-script %}
    {% endblock extra-script %}

</head>

<body>

{% block content %}

{% endblock %}
{% block scripts %}
<!-- Bootstrap -->
<!-- Bootstrap JS y dependencias -->
<!--<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>-->

<!--    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
{% endblock %}
{% block extrajs %}
{% endblock extrajs %}

</body>

</html>

templates/capturaweb/layouts/form_borrar.html
{% extends "capturaweb/layouts/base.html" %}

{% block title %} {{ title }} {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="pcoded-content">
        <div class="pcoded-inner-content">
            <!-- [ breadcrumb ] start -->
            <div class="page-header">
                <div class="page-block">
                    <div class="row align-items-center">
                        <div class="col-md-12">
                            <div class="page-header-title">
                                <h5 class="m-b-10">{{ title }}</h5>
                            </div>
                            <ul class="breadcrumb">
                                <li class="breadcrumb-item"><a href="/"><i class="feather icon-home"></i></a></li>
                                <li class="breadcrumb-item"><a href="{{ url_general }}">{{ anterior }}</a></li>
                                <li class="breadcrumb-item"><a href="">Borrar {{ object.titulo }}</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!-- [ breadcrumb ] end -->
            <div class="main-body">
                <div class="card border-light shadow-sm">
                    <div class="page-wrapper">
                        <!-- [ Main Content ] start -->
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="card">
                                    <div class="card-header">
                                        <h5>{{ comentario }}</h5>
                                    </div>
                                    <div class="card-body">
                                        <div class="row">
                                            <div class="col-md-12">
                                                <form action="" method="POST">
                                                    {% csrf_token %}
                                                    {% if form.errors %}
                                                        {% for field in form %}
                                                            {% for error in field.errors %}
                                                                <li>{{ error }}</li>
                                                            {% endfor %}
                                                        {% endfor %}
                                                    {% endif %}
                                                    <div class="alert alert-danger alert-dismissible">
                                                        <h6><i class="icon fas fa-ban"></i>&nbsp;{{ mensaje }}</h6>
                                                    </div>
                                                    <div class="card-footer">
                                                        <button type="submit" class="btn btn-danger btn-flat">
                                                            Si, acepto
                                                        </button>
                                                        <a href="{{ url_general }}"
                                                           class="btn btn-secondary btn-flat"> Cancelar</a>
                                                    </div>
                                                </form>

                                            </div>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                        <!-- [ Main Content ] end -->
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

{% endblock javascripts %}

templates/capturaweb/layouts/lista.html
{% extends "capturaweb/layouts/base.html" %}
{% load static %}
{% block title %}{{ title }}{% endblock %}

{% block scripst %}
    <link rel="stylesheet"
          href="{% static 'capturadora/librerias/datatables-1.10.20/css/dataTables.bootstrap4.min.css' %}"/>
    <link rel="stylesheet"
          href="{% static 'capturadora/librerias/datatables-1.10.20/plugins/responsive-2.2.3/css/responsive.bootstrap4.min.css' %}"/>
    <script src="{% static 'capturadora/librerias/datatables-1.10.20/js/jquery.dataTables.js' %}"></script>
    <script src="{% static 'capturadora/librerias/datatables-1.10.20/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'capturadora/librerias/datatables-1.10.20/plugins/responsive-2.2.3/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'capturadora/librerias/datatables-1.10.20/plugins/responsive-2.2.3/js/responsive.bootstrap4.min.js' %}"></script>
{% endblock scripst %}

{% block content %}
    <!-- [ breadcrumb ] start -->
    {% block breadcrumb %}{% endblock breadcrumb %}
    <!-- [ breadcrumb ] end -->
    {% block tabla %}{% endblock tabla %}
{% endblock content %}
<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
    <script type="application/javascript">
        $(function () {
            $('#data').DataTable({
                responsive: true,
                autoWidth: false
            });
        });
    </script>
{% endblock javascripts %}