config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.capturaweb.urls")),
]

core/capturaweb/forms.py
from django import forms

from core.capturaweb.models import Grabacion, GrabacionProgramada

FORMATO = ((1, "AUDIO-VIDEO"), (2, "AUDIO"))


class DatosGrabacionForm(forms.ModelForm):
    TIPO = ((1, "CONTINUA"), (2, "SEGMENTADA"))
    CONVERTIR = ((True, "SI"), (False, "NO"))

    tipo_grabacion = forms.ChoiceField(choices=TIPO, initial='1',
                                       widget=forms.RadioSelect(attrs={'class': 'btn-check'}))
    convertida = forms.ChoiceField(choices=CONVERTIR, initial=False,
                                   widget=forms.RadioSelect(attrs={'class': 'btn-check'}))
    segmento = forms.CharField(max_length=4, initial=10, required=False,
                               widget=forms.TextInput(attrs={'style': 'visibility: hidden;'}))

    class Meta:
        model = Grabacion
        fields = ['titulo', 'convertida', 'tipo_grabacion']
        widgets = {
            'titulo': forms.TextInput(attrs={'class': 'form-control'}),
        }


class ProgramarGrabacionForm(forms.ModelForm):
    TIPO = ((1, "CONTINUA"), (2, "SEGMENTADA"))
    CONVERTIR = ((True, "SI"), (False, "NO"))

    tipo_grabacion = forms.ChoiceField(choices=TIPO, initial='1',
                                       widget=forms.RadioSelect(attrs={'class': 'btn-check'}))
    convertida = forms.ChoiceField(choices=CONVERTIR, initial=False,
                                   widget=forms.RadioSelect(attrs={'class': 'btn-check'}))
    segmento = forms.CharField(max_length=4, initial=60, required=False,
                               widget=forms.TextInput(attrs={'class': 'form-control', 'style': 'visibility: hidden;'}))

    class Meta:
        model = GrabacionProgramada
        fields = ['titulo', 'hora_inicio', 'hora_fin', 'lunes', 'martes', 'miercoles', 'jueves', 'viernes',
                  'sabado', 'domingo', 'convertida', 'tipo_grabacion', 'activa']
        widgets = {
            'titulo': forms.TextInput(attrs={'class': 'form-control'}),
            'hora_inicio': forms.TimeInput(
                attrs={'class': 'form-control',
                       'placeholder': 'Select a date',
                       'type': 'time'
                       }),
            'hora_fin': forms.TimeInput(
                attrs={'class': 'form-control',
                       'placeholder': 'Select a date',
                       'type': 'time'
                       }),
            'lunes': forms.CheckboxInput(
                attrs={'class': 'btn-check',
                       'type': 'checkbox'
                       }),
            'martes': forms.CheckboxInput(
                attrs={'class': 'btn-check',
                       'type': 'checkbox'
                       }),
            'miercoles': forms.CheckboxInput(
                attrs={'class': 'btn-check',
                       'type': 'checkbox'
                       }),
            'jueves': forms.CheckboxInput(
                attrs={'class': 'btn-check',
                       'type': 'checkbox'
                       }),
            'viernes': forms.CheckboxInput(
                attrs={'class': 'btn-check',
                       'type': 'checkbox'
                       }),
            'sabado': forms.CheckboxInput(
                attrs={'class': 'btn-check',
                       'type': 'checkbox'
                       }),
            'domingo': forms.CheckboxInput(
                attrs={'class': 'btn-check',
                       'type': 'checkbox'
                       }),
            'activa': forms.CheckboxInput(
                attrs={'class': 'btn-check',
                       'type': 'checkbox'
                       }),
        }


class DescargaForm(forms.Form):
    url = forms.CharField(label="URL", max_length=200, required=True)
    formato = forms.ChoiceField(widget=forms.RadioSelect, choices=FORMATO, required=True)

templates/descargar.html
{% extends "base.html" %} {% load static %} {% block content %}
{% block title %}DESCARGA-YOUTUBE{% endblock %}
<div class="jumbotron">
    <div class="modal-content">
        <div class="modal-body">
            <div class="row modal-title">
                <div class="col-xl-12">
                    <div class="row">
                        <h3 id="estado">
                        </h3>
                    </div>
                    <div class="row">
                        <div class="col-xl-9">
                            <h3 id="titulo">
                            </h3>
                        </div>
                        <div class="col-xl-3">
                            <h3 id="progreso" style="text-align: right;">
                            </h3>
                        </div>
                    </div>
                </div>
            </div>
            <form method="post">
                {% csrf_token %}
                {{ form.non_field_errors }}
                <div class="form-control">
                    {{ form.url.errors }}
                    <legend for="{{ form.url.id_for_label }}">
                        URL: {{ form.url }}
                    </legend>
                </div>
                {% if ocupada %} OCUPADA {% endif %}
                <br>
                    <div class="form-control">
                        <legend>
                            Formato:
                        </legend>
                        {% for radio in form.formato %}
                        <label class="text">
                            {{ radio.tag }} {{ radio.choice_label }}
                        </label>
                        <br>
                            {% endfor %}
                        </br>
                    </div>
                    <br>
                        <div class="modal-footer">
                            <input class="btn btn-success descargar" name="descargar" type="submit" value="DESCARGAR"/>
                        </div>
                    </br>
                </br>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<!--<script type="text/javascript">
        window.onload=function() {
            setInterval(function(){ 
                var des_url = $("#id_url").val();
                var request = $.ajax({
                type: "POST",
                url: "{% url 'datos' %}",
                data: {"dir_url":des_url},
            });
            request.done(function(datos) {
                console.log("ok-info")
                $("#estado").html(datos.label);
                $("#titulo").html(datos.titulo);
                $("#progreso").html(datos.progreso);
              });
             }, 1000);
        };
    </script>-->
{% endblock %}